version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      # - db
      - redis 
    environment:
      - SECRET_KEY=${SECRET_KEY}    
      - ALGORITHM=${ALGORITHUM}   
      - DATABASE_URL=${MONGO_URL} 
      # - DATABASE_URL=mongodb://db:27017/organization
      - REDIS_URL=redis://redis:6379 
    volumes:
      - .:/app  

  # db:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./data:/data/db

  redis: 
    image: redis:alpine  
    ports:
      - "6379:6379"  
